---
- name: Setup challenges EC2 instances for use with ECS
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - challenges

- name: Provision challenges EC2 instances for use with ECS
  hosts: all
  become: true
  roles:
    - challenges
