---
- name: Setup EC2 instances for use with ECS
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - scoreboard
    - challenges

- name: Provision EC2 hosts for use with ECS
  hosts: all
  become: true
  roles:
    - scoreboard
    - challenges
