---
- name: Setup EC2 instances for use with ECS
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - scoreboard
  tasks:
    - name: Setup ECS cluster for challenges
      ecs_cluster:
        name: neverlan_challenges
        state: present
        region: us-east-1

- name: Provision EC2 hosts for use with ECS
  hosts: all
  become: true
  roles:
    - scoreboard
