---
- name: Setup ECS cluster for scoreboard
  ecs_cluster:
    name: neverlan_scoreboard
    state: present
    region: us-east-1

- name: Setup ECS task definition for scoreboard on neverlan_ctf cluster
  ecs_taskdefinition:
    containers:

    - name: ctfd
      cpu: 50
      essential: true
      image: neverlanctf/ctfd
      memory: 128
      portMappings:
        - containerPort: 8000
          hostPort: 80
      volumesFrom:
        - sourceContainer: datastore
      links:
        - "mariadb:mariadb"
      environment:
        - name: MYSQL_USER
          value: "{{ mysql_user }}"
        - name: MYSQL_PASSWORD
          value: "{{ mysql_password }}"
      #command:
      #  - tail
      #  - "-f"
      #  - /dev/null

    - name: mariadb
      cpu: 50
      essential: true
      image: mariadb
      memory: 512
      volumesFrom:
        - sourceContainer: datastore
      environment:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "true"
        - name: MYSQL_DATABASE
          value: ctfd
        - name: MYSQL_USER
          value: "{{ mysql_user }}"
        - name: MYSQL_PASSWORD
          value: "{{ mysql_password }}"

    - name: datastore
      cpu: 10
      essential: true
      image: busybox
      memory: 128
      command:
        - tail
        - "-f"
        - /dev/null
      mountPoints:
      - sourceVolume: logs
        containerPath: /var/lib/mysql
      - sourceVolume: mysql
        containerPath: /opt/CTFd/CTFd/logs

    volumes:
      - name: logs
        host:
          sourcePath: /opt/CTFd/CTFd/logs
      - name: mysql
        host:
          sourcePath: /var/lib/mysql

    state: present
    family: scoreboard
    region: us-east-1

- name: Provision ECS container instance for scoreboard
  ec2:
    instance_type: t2.micro
    image: "{{ ami_id }}"
    key_name: neverlanctf
    wait: true
    exact_count: 1
    count_tag:
      Name: neverlan_scoreboard
    instance_tags:
      Name: neverlan_scoreboard
    vpc_subnet_id: subnet-898096a1
    assign_public_ip: yes
    instance_profile_name: ecsInstanceRole
    region: us-east-1
    group: neverlanctf
    termination_protection: yes
  register: scoreboard
  notify: Assign Elastic IP to scoreboard EC2 instance
