---
- name: Setup ECS service for console on challenges cluster
  ecs_service:
    name: console
    cluster: neverlan_challenges
    task_definition: console
    state: present
    desired_count: 1

- name: Setup ECS service for sql_fun1 on challenges cluster
  ecs_service:
    name: sql_fun1
    cluster: neverlan_challenges
    task_definition: sql_fun1
    state: present
    desired_count: 1

- name: Setup ECS service for sql_fun2 on challenges cluster
  ecs_service:
    name: sql_fun2
    cluster: neverlan_challenges
    task_definition: sql_fun2
    state: present
    desired_count: 1

- name: Setup ECS service for javascript_password on challenges cluster
  ecs_service:
    name: javascript_password
    cluster: neverlan_challenges
    task_definition: javascript_password
    state: present
    desired_count: 1

- name: Setup ECS service for bringing_it_all_together on challenges cluster
  ecs_service:
    name: bringing_it_all_together
    cluster: neverlan_challenges
    task_definition: bringing_it_all_together
    state: present
    desired_count: 1

- name: Setup ECS service for know_your_shortcuts on challenges cluster
  ecs_service:
    name: know_your_shortcuts
    cluster: neverlan_challenges
    task_definition: know_your_shortcuts
    state: present
    desired_count: 1
