---
- name: Setup ECS cluster for challenges
  ecs_cluster:
    name: neverlan_challenges
    state: present
    region: us-east-1

- name: Setup ECS service for console on challenges cluster
  ecs_service:
    name: console
    cluster: neverlan_challenges
    task_definition: console:1
    state: present
    desired_count: 1

- name: Setup ECS service for runme on challenges cluster
  ecs_service:
    name: runme
    cluster: neverlan_challenges
    task_definition: runme:1
    state: present
    desired_count: 1

- name: Setup ECS service for sql_fun1 on challenges cluster
  ecs_service:
    name: sql_fun1
    cluster: neverlan_challenges
    task_definition: sql_fun1:1
    state: present
    desired_count: 1

- name: Setup ECS service for sql_fun2 on challenges cluster
  ecs_service:
    name: sql_fun2
    cluster: neverlan_challenges
    task_definition: sql_fun2:1
    state: present
    desired_count: 1

- name: Provision ECS container instance for challenges
  ec2:
    instance_type: t2.micro
    image: "{{ ami_id }}"
    key_name: neverlanctf
    wait: true
    exact_count: 1
    count_tag:
      Name: neverlan_challenges
    instance_tags:
      Name: neverlan_challenges
    vpc_subnet_id: subnet-898096a1
    assign_public_ip: yes
    instance_profile_name: ecsInstanceRole
    region: us-east-1
    group: neverlanctf
    termination_protection: yes
  register: challenges
  notify: Assign Elastic IP to challenges EC2 instance
