---
- name: Setup ECS cluster for challenges
  ecs_cluster:
    name: neverlan_challenges
    state: present
    region: us-east-1

- include: setup-task-definitions.yml
- include: setup-services.yml

- name: Provision ECS container instance for challenges
  ec2:
    instance_type: t2.micro
    image: "{{ ami_id }}"
    key_name: neverlanctf
    wait: true
    exact_count: 2
    count_tag:
      Name: neverlan_challenges
    instance_tags:
      Name: neverlan_challenges
    vpc_subnet_id: subnet-898096a1
    instance_profile_name: ecsInstanceRole
    region: us-east-1
    group: neverlanctf
  register: challenges
  notify: Add ECS container instances to challenges ELB
