---
- name: Restart ecs step 1
  shell: stop ecs
  notify: Restart ecs step 2

- name: Restart ecs step 2
  file:
    path: /var/lib/ecs/data/ecs_agent_data.json
    state: absent
  notify: Restart ecs step 3

- name: Restart ecs step 3
  shell: start ecs

- name: Add ECS container instances to challenges ELB
  ec2_elb:
    ec2_elbs: challenges
    instance_id: "{{ item.id }}"
    region: us-east-1
    state: present
  with_items: challenges.instances
